book/urls.py
from django.urls import path
from book.views import get_books


app_name = 'book'

urlpatterns = [
    path('', get_books, name='get_books'),
]

bookly/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/books/', include("book.urls")),
    path('add_book/', include("add_book.urls")),
    path('edit_book/', include("edit_delete_book.urls")),
    path('', include("main.urls")),
    path('review/', include("review.urls")),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('login/', user_views.login_user, name='login'),
    path('register/', user_views.register, name='register'),
    path('logout/', user_views.logout_user, name='logout'),
    path('profile/', user_views.profile, name='profile'),
    path('user-review/', user_views.show_user_review, name='user-review'),
    path('auth/', include('authentication.urls')),
    path('profile-json/', user_views.show_profile_json, name='profile-json'),
    path('update-profile/', user_views.update_profile_flutter, name='update-profile'),
    path('get-user-review/', user_views.get_user_review, name='get-user-review')
]

main/urls.py
from django.urls import path
from main.views import show_main

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
]

users/urls.py
from django.urls import path
from users.views import register, login_user, logout_user, get_user_review, show_profile_json

app_name = 'users'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('get_user_review/', get_user_review, name='get_user_review'),
    path('show_profile_json/', show_profile_json, name='show_profile_json'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(null= True, default=None, blank=True)
    first_name = models.CharField(max_length=255, null=True, default=None, blank=True)
    last_name = models.CharField(max_length=255, null=True, default=None, blank=True)
    address = models.CharField(max_length=255, null=True, default=None, blank=True)
    phone_number = models.CharField(max_length=255, null=True, default=None, blank=True)
    
    LIST_GENDER = (
        ('Male', 'Male'),
        ('Female', 'Female')
    )
    gender = models.CharField(max_length=255, null=True, choices=LIST_GENDER, default=None, blank=True)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from users.models import Profile

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [  
            'first_name', 
            'last_name', 
            'address', 
            'phone_number',
            'gender',
            'email'
            ]

        labels = {
            'first_name':'First Name',
            'last_name': "Last Name",
            'phone_number': 'Phone Number'
        }

        widgets = {
            'first_name': forms.TextInput(
                attrs={
                    'class': 'form-control my-2 border border-primary-subtle',
                    'required': False,
                    'blank': True
                }
            ),

            'last_name': forms.TextInput(
                attrs={
                    'class': 'form-control my-2 border border-primary-subtle',
                    'required': False,
                    'blank': True
                }
            ),

            'address': forms.Textarea(
                attrs={
                    'class': 'form-control my-2 border border-primary-subtle',
                    'rows': '2',
                    'required': False,
                    'blank': True
                }
            ),

            'phone_number': forms.TextInput(
                attrs={
                    'class': 'form-control my-2 border border-primary-subtle',
                    'required': False,
                    'blank': True
                }
            ),

            'gender': forms.Select(
                attrs={
                    'class': 'form-control my-2 border border-primary-subtle',
                    'required': False,
                    'blank': True
                }
            ),

            'email': forms.EmailInput(
                attrs={
                    'class': 'form-control my-2 border border-primary-subtle',
                    'required': False,
                    'blank': True
                }
            ),
        }

users/views.py
import json
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from users.forms import ProfileUpdateForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages 
from django.contrib.auth.decorators import login_required
from review.models import Review
from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from django.core import serializers
from users.models import Profile
from book.models import Book
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('login')
    context = {'form':form}
    return render(request, 'register.html', context)


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('main:show_main')
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    return redirect('login')

@login_required(login_url='/login')
def profile(request):
    profile_form = ProfileUpdateForm(instance=request.user.profile)

    if request.method == 'POST':
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Your account has been updated!')
            return redirect('profile')

    context = {
        'username': request.user.username,
        'profile_form': profile_form
    }
    return render(request, 'profile.html', context)

def get_user_review(request):
    user_review = Review.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', user_review))

def show_user_review(request):
    return render(request, 'user_review.html')

def show_profile_json (request):
    data = Profile.objects.filter(user = request.user)
    return HttpResponse(serializers.serialize("json", data))

@csrf_exempt
def update_profile_flutter(request):
    if request.method == 'POST':
        data = json.loads(request.body)

        profile = Profile.objects.get(user=request.user)
        
        profile.email = data["email"]
        profile.first_name = data["first_name"]
        profile.last_name = data["last_name"]
        profile.address = data["address"]
        profile.phone_number = data["phone_number"]
        profile.gender = data["gender"]
        profile.save()

        return JsonResponse({"status": "success"}, status=200)

    else:
        return JsonResponse({"status": "error"}, status=401)

users/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Don't have an account yet? <a href="{% url 'register' %}">Register Now</a>

</div>

{% endblock content %}

users/templates/profile.html
{% extends 'base.html' %}

{% block meta %}
    <title>Profile</title>

    <style>
        #border-personal{
            background-color: white;
            margin-left: 20%;
            margin-right: 20%;
        }

    </style>
{% endblock meta %}

{% block content %}
    <div class="container-flow">
        <form method="POST">
            {% csrf_token %}
            <div class="content-section">
                <div class="mx-auto mt-5">
                    <div class="border border-primary rounded-4" id="border-personal">
                        <div class="row my-3 ms-4">
                            <div class="col-9">
                                <a href="{% url 'main:show_main' %}" style="text-decoration: none; font-size: 130%;">
                                    <i class="bi bi-arrow-left"></i>
                                    Home
                                </a>
                            </div>
                            <div class="col ms-4">
                                <a href="{% url 'user-review' %}" style="text-decoration: none; font-size: 130%; text-align: right;">
                                    See your reviews
                                    <i class="bi bi-arrow-right"></i>
                                </a>
                            </div>
                        </div>
                        <h4 class="personal-info my-3 ms-5">User Info</h4>
    
                        <div class="row gx-5">
                            <div class="col">
                                <div class="form-group ms-5">
                                    <b>Username</b>
                                    <div class="form-control my-2 border border-primary-subtle">
                                        {{ username }}
                                    </div>
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group me-5">
                                    <b>{{ profile_form.email.label }}</b>
                                    {{ profile_form.email }}
                                </div>
                            </div>
                        </div>
    
                        <div class="row gx-5">
                            <div class="col">
                                <div class="form-group ms-5">
                                    <b>{{ profile_form.first_name.label }}</b>
                                    {{ profile_form.first_name }}
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group me-5">
                                    <b>{{ profile_form.last_name.label }}</b>
                                    {{ profile_form.last_name }}
                                </div>
                            </div>
                        </div>
        
                        <div class="row gx-5">
                            <div class="col">
                                <div class="form-group ms-5">
                                    <b>{{ profile_form.gender.label }}</b>
                                    {{ profile_form.gender }}
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group me-5">
                                    <b>{{ profile_form.phone_number.label }}</b>
                                    {{ profile_form.phone_number }}
                                </div>
                            </div>
                        </div>
    
                        <div class="row">
                            <div class="col" id="address">
                                <div class="form-group mx-5 mb-4">
                                    <b>{{ profile_form.address.label }}</b>
                                    {{ profile_form.address }}
                                </div>
                            </div>
                        </div>

                        <div class="text-center mt-3 mb-4">
                            <div class="form-group">
                                <button class="btn btn-primary" type="submit" style="width: 80%;">Save Profile</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Register</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

users/templates/show_user_review.html
{% extends 'base.html' %}

{% block meta %}
<title>User Review</title>
{% endblock meta %}

{% block content %}

    <div class="container">
        <div class="row " id="item_cards"></div>
    </div>

    <script>
        async function getUserReview() {
            return fetch("{% url 'users:get_user_review' %}").then((res) => res.json())
        }

        async function getBooks() {
            return fetch("{% url 'book:get_books' %}").then((res) => res.json())
        }

        async function refreshCatalog() {
            let htmlString = '';
            document.getElementById("user_review_catalog").innerHTML = "";
            const user_reviews = await getUserReview();
            const books = await getBooks();

            user_reviews.forEach(review => {
                books.forEach(book => {
                    if(review.fields.book == book.pk) {
                        htmlString += `<div class="card" style="width: 19rem;">
                            <div class="card-body">
                                <h5 class="card-title">${book.fields.name} (${ book.fields.year })</h5>
                                <h6 class="card-subtitle mb-2 text-body-secondary">${ book.fields.author }</h6>
                                <ul>
                                    <li>Genre: ${book.fields.genre}</li>
                                    <li>Rating: ${book.fields.rating}</li>
                                    <li>Price: $${book.fields.price}</li>
                                </ul>
                                <a href="{#}" class="btn btn-primary ms-5";>See Review</a>
                            </div>
                        </div>`;
                    }
                })
            })
            document.getElementById("user_review_catalog").innerHTML += htmlString;
        }
        refreshCatalog();
    </script>
{% endblock content %}

users/templates/user_review.html
{% extends 'base.html' %}

{% block meta %}
<title>User Review</title>
{% endblock meta %}

{% block content %}

    <div class="container">
        <div class="row mt-5">
            <div class="col">
                <h1>{{user.username}}'s reviews</h1>
            </div>
        </div>
        <div class="d-flex grid gap-4 flex-wrap m-4" id="user_review_catalog"></div>
    </div>

    <script>
        async function getUserReview() {
            return fetch("{% url 'users:get_user_review' %}").then((res) => res.json())
        }

        async function getBooks() {
            return fetch("{% url 'book:get_books' %}").then((res) => res.json())
        }

        async function refreshCatalog() {
            let htmlString = '';
            document.getElementById("user_review_catalog").innerHTML = "";
            const user_reviews = await getUserReview();
            const books = await getBooks();
            const bookList = [];

            user_reviews.forEach(review => {
                books.forEach(book => {
                    if(review.fields.book == book.pk && !bookList.includes(book.pk)) {
                        bookList.push(book.pk);
                        htmlString += `<div class="card" style="width: 19rem;">
                            <div class="card-body">
                                <h5 class="card-title">${book.fields.name} (${ book.fields.year })</h5>
                                <h6 class="card-subtitle mb-2 text-body-secondary">${ book.fields.author }</h6>
                                <ul>
                                    <li>Genre: ${book.fields.genre}</li>
                                    <li>Rating: ${book.fields.rating}</li>
                                    <li>Price: $${book.fields.price}</li>
                                </ul>
                            </div>
                        </div>`
                    }
                })
            })
            document.getElementById("user_review_catalog").innerHTML += htmlString;
        }
        refreshCatalog();
    </script>
{% endblock content %}