book/urls.py
from django.urls import path
from book.views import get_books


app_name = 'book'

urlpatterns = [
    path('', get_books, name='get_books'),
]

bookly/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/books/', include("book.urls")),
    path('add_book/', include("add_book.urls")),
    path('edit_book/', include("edit_delete_book.urls")),
    path('', include("main.urls")),
    path('review/', include("review.urls")),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('login/', user_views.login_user, name='login'),
    path('register/', user_views.register, name='register'),
    path('logout/', user_views.logout_user, name='logout'),
    path('profile/', user_views.profile, name='profile'),
    path('user-review/', user_views.show_user_review, name='user-review'),
    path('auth/', include('authentication.urls')),
    path('profile-json/', user_views.show_profile_json, name='profile-json'),
    path('update-profile/', user_views.update_profile_flutter, name='update-profile'),
    path('get-user-review/', user_views.get_user_review, name='get-user-review')
]

edit_delete_book/urls.py
from django.urls import path
from edit_delete_book.views import *

app_name = 'edit_delete_book'

urlpatterns = [
    path('show/<int:book_id>/', show, name='show'),
    path('edit/<int:book_id>/', edit_book, name='edit_book'),
    path('get_book_json/<int:book_id>/', get_book_json, name='get_book_json'),
    path('delete_book_flutter/', delete_book_flutter, name='delete_book_flutter'),
    path('edit_book_flutter/<int:book_id>', edit_book_flutter, name='edit_book_flutter'),
]

main/urls.py
from django.urls import path
from main.views import show_main

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
]

review/urls.py
from django.urls import path
from review.views import *
from review.views import add_review_flutter

app_name = 'review'

urlpatterns = [
    path('create-review-ajax/<int:book_id>/', add_review_ajax, name='add_review_ajax'),
    path('get-review/<int:book_id>/', get_review_json, name='get_review_json'),
    path('show-reviews/<int:book_id>/', show_reviews, name='show_reviews'),
    path('add-review/<int:book_id>/', add_review, name='add_review'),
    path('show-reviews-specific-user/', show_reviews_specific_user, name='show_reviews_specific_user'),
    path('get-review-json-by-user-id/', get_review_json_by_user_id, name='get_review_json_by_user_id'),
    path('show-reviews-specific-user/edit-reviews/<int:book_id>/', edit_reviews, name='edit_reviews'),
    path('show-reviews-specific-user/delete-item-ajax/<int:review_id>', delete_item_ajax, name='delete_item_ajax'),
    path('show-reviews-specific-user/delete-item-flutter/', delete_item_flutter, name='delete_item_flutter'),
    path('show-reviews-specific-user/edit-review-flutter/', edit_review_flutter, name='delete_item_flutter'),
    path('add-review-flutter/<int:book_id>/', add_review_flutter, name='add_review_flutter'),
]

edit_delete_book/models.py
from django.db import models
from django.db import models
from book.models import Book

edit_delete_book/views.py
import json
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponseNotFound, HttpResponseRedirect, JsonResponse
from django.views.decorators.http import require_http_methods
from edit_delete_book.forms import BookForm
from django.urls import reverse
from book.models import Book
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.core import serializers

from review.models import Review

def show(request, book_id):
    book = Book.objects.get(pk=book_id)
    forms = BookForm(request.POST or None, instance=book)
    context = {
        'book': book,
        'forms': forms,
    }
    return render(request, 'show.html', context)

def get_book_json(request, book_id):
    try:
        book = Book.objects.get(pk=book_id)
    except Book.DoesNotExist:
        # Handle the case where the book doesn't exist
        return HttpResponseNotFound("Book not found")

    # Serialize the book data
    serialized_book = serializers.serialize('json', [book])

    # Convert the serialized data to a Python dictionary
    book_data = serialized_book[1:-1]  # Remove square brackets from serialized data
    book_dict = json.loads(book_data)

    # Return the book data as JSON response
    return JsonResponse(book_dict)

def get_review_json(request, book_id):
    book = Book.objects.get(pk=book_id)
    product_item = Review.objects.filter(book=book)
    return HttpResponse(serializers.serialize('json', product_item, use_natural_foreign_keys=True, use_natural_primary_keys=True))

@csrf_exempt
def edit_book(request, book_id):
    # Temukan buku berdasarkan ID
    book = Book.objects.get(pk=book_id)

    if request.method == 'POST':
        # Ambil data yang dikirim dari form
        name = request.POST.get('name')
        author = request.POST.get('author')
        price = request.POST.get('price')
        year = request.POST.get('year')
        genre = request.POST.get('genre')

        # Update atribut-atribut buku
        book.name = name
        book.author = author
        book.price = price
        book.year = year
        book.genre = genre

        # Simpan perubahan
        book.save()

        # Kirim respons JSON sebagai konfirmasi
        response_data = {
            'message': 'Detail buku berhasil diperbarui.',
        }
        return JsonResponse(response_data)
    
@csrf_exempt
def delete_book_flutter(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        product = get_object_or_404(Review, pk=data['review_id'])
        product.delete()
        return JsonResponse({"status": True}, status = 200)
    return JsonResponse ({"status": True}, status = 200)

@csrf_exempt
@require_http_methods(["PUT"])
def edit_book_flutter(request, book_id):
    try:
        book = Book.objects.get(pk=book_id)
    except Book.DoesNotExist:
        # Handle the case where the book doesn't exist
        return JsonResponse({"error": "Book not found"}, status=404)

    if request.method == 'PUT':
        data = request.body.decode('utf-8')
        book_data = json.loads(data)

        # Update atribut-atribut buku dengan data yang diterima dari Flutter
        if 'name' in book_data:
            book.name = book_data['name']
        if 'author' in book_data:
            book.author = book_data['author']
        if 'price' in book_data:
            book.price = book_data['price']
        if 'year' in book_data:
            book.year = book_data['year']

        # Simpan perubahan
        book.save()

        # Kirim respons JSON sebagai konfirmasi
        return JsonResponse({"message": "Book details updated successfully"})

    return JsonResponse({"error": "Invalid request method"}, status=400)

edit_delete_book/templates/show.html
    {% extends 'base.html' %}
    {% load static %}

    {% block content %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <body>
        <a href="{% url 'main:show_main' %}" class="btn btn-light">
            <i class="bi bi-arrow-left"></i> Back
        </a>
        <div class="BookPage_GridContainer" id="BookDetails"></div>
    </body>

    <div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="editModalLabel">Edit Book</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="bookForm" method="POST">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name" class="form-label">Judul</label>
                            <input type="text" name="name" class="form-control" value="{{ book.name }}">
                        </div>
                        <div class="mb-3">
                            <label for="author" class="form-label">Penulis</label>
                            <input type="text" name="author" class="form-control" value="{{ book.author }}">
                        </div>
                        <div class="mb-3">
                            <label for="price" class="form-label">Harga</label>
                            <input type="text" name="price" class="form-control" value="{{ book.price}}">
                        </div>
                        <div class="mb-3">
                            <label for="year" class="form-label">Tahun</label>
                            <input type="text" name="year" class="form-control" value="{{ book.year }}">
                        </div>
                        <div class="mb-3">
                            <label for="genre" class="form-label">Genre</label>
                            <input type="text" name="genre" class="form-control" value="{{ book.genre }}">
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Batal</button>
                            <button type="button" class="btn btn-secondary" id="button_edit" data-dismiss="modal">Simpan Edit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script>
        async function getBook() {
            return fetch("{% url 'edit_delete_book:get_book_json' book.pk %}").then((res) => res.json())
        }
        async function getReviews() {
            return fetch("{% url 'review:get_review_json' book.pk %}").then((res) => res.json())
         }
        async function displayBookDetail() {
            document.getElementById("BookDetails").innerHTML = ""
            const book = await getBook();
            const reviews = await getReviews();
            let HTMLString = `
            <div class="container">
                <div class="row">
                    <div class="col-md-8">
                        <div class="book-profile">
                            <h1><strong>${book.fields.name}</strong></h1>
                            <br><br>
                            <p><strong>Penulis: </strong> ${book.fields.author}</p>
                            <p><strong>Rating: </strong> ${book.fields.rating}</p>
                            <p><strong>Reviews: </strong> ${book.fields.reviews}</p>
                            <p><strong>Price: </strong> $ ${book.fields.price}</p>
                            <p><strong>Tahun terbit: </strong> ${book.fields.year}</p>
                            <p><strong>Genre: </strong> ${book.fields.genre}</p>
                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#editModal" >Edit</button>
                        </div>
                    </div>
                </div> 
            </div>
            `;
            reviews.forEach((review) => {
                HTMLString += `
                <div class="review">
                    <h3> ${review.fields.user} :</h3>
                    <p>Rating: ${review.fields.rating}</p>
                    <h6>${review.fields.reviews}</h6>
                </div>
                `
            })
            document.getElementById("BookDetails").innerHTML = HTMLString
        }
        displayBookDetail()

        
        function editBook() {
            fetch("{% url 'edit_delete_book:edit_book' book.id %}", {
                method: "POST",
                body: new FormData(document.getElementById("bookForm")),
            }).then(displayBookDetail)

            return false;
        }
        document.getElementById("button_edit").onclick = editBook
        
    </script>

    <style>
        .book-profile {
            background-color: #f8f8f8;
            border: 1px solid #ddd;
            padding: 20px;
            margin: 20px;
            border-radius: 5px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }

        .book-profile h1 {
            font-size: 24px;
            color: #333;
        }

        .book-profile p {
            font-size: 16px;
            color: #666;
        }

        .edit-button {
            background-color: #007bff;
            color: #fff;
            padding: 8px 16px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        .modal-header .close {
            display: none;
        }

        .review {
            border: 1px solid #e0e0e0;
            border-radius: 5px;
            padding: 10px;
            margin-bottom: 20px;
            background-color: #fff;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        
        .review h3 {
            font-size: 18px;
            margin: 0;
            color: #333;
        }
        
        .review p {
            font-size: 16px;
            color: #666;
        }
        
        .separator {
            border-top: 1px solid #e0e0e0;
            margin: 20px 0;
        }
        
        .reviews {
            margin-top: 20px;
        }

    </style>

    </div>
    {% endblock %}