add_book/urls.py
from django.urls import path
from add_book.views import *

app_name = 'add_book'

urlpatterns = [
    path('get_book/', get_book, name='get_book'),
    path('add_book/', add_book, name='add_book')
]

book/urls.py
from django.urls import path
from book.views import get_books


app_name = 'book'

urlpatterns = [
    path('', get_books, name='get_books'),
]

bookly/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/books/', include("book.urls")),
    path('add_book/', include("add_book.urls")),
    path('edit_book/', include("edit_delete_book.urls")),
    path('', include("main.urls")),
    path('review/', include("review.urls")),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('login/', user_views.login_user, name='login'),
    path('register/', user_views.register, name='register'),
    path('logout/', user_views.logout_user, name='logout'),
    path('profile/', user_views.profile, name='profile'),
    path('user-review/', user_views.show_user_review, name='user-review'),
    path('auth/', include('authentication.urls')),
    path('profile-json/', user_views.show_profile_json, name='profile-json'),
    path('update-profile/', user_views.update_profile_flutter, name='update-profile'),
    path('get-user-review/', user_views.get_user_review, name='get-user-review')
]

main/urls.py
from django.urls import path
from main.views import show_main

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
]

review/urls.py
from django.urls import path
from review.views import *
from review.views import add_review_flutter

app_name = 'review'

urlpatterns = [
    path('create-review-ajax/<int:book_id>/', add_review_ajax, name='add_review_ajax'),
    path('get-review/<int:book_id>/', get_review_json, name='get_review_json'),
    path('show-reviews/<int:book_id>/', show_reviews, name='show_reviews'),
    path('add-review/<int:book_id>/', add_review, name='add_review'),
    path('show-reviews-specific-user/', show_reviews_specific_user, name='show_reviews_specific_user'),
    path('get-review-json-by-user-id/', get_review_json_by_user_id, name='get_review_json_by_user_id'),
    path('show-reviews-specific-user/edit-reviews/<int:book_id>/', edit_reviews, name='edit_reviews'),
    path('show-reviews-specific-user/delete-item-ajax/<int:review_id>', delete_item_ajax, name='delete_item_ajax'),
    path('show-reviews-specific-user/delete-item-flutter/', delete_item_flutter, name='delete_item_flutter'),
    path('show-reviews-specific-user/edit-review-flutter/', edit_review_flutter, name='delete_item_flutter'),
    path('add-review-flutter/<int:book_id>/', add_review_flutter, name='add_review_flutter'),
]

main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core import serializers


from book.models import Book

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseNotFound
from django.urls import reverse
from book.models import Book

@login_required(login_url='/login')
def show_main(request):
    books = Book.objects.all()
    context = {
        'name': request.user.username,
        'books': books
    }
    return render (request, "main.html", context)

main/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Main Page</title>

<!-- Bootstrap icon--> 
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700">

<style>
    .ReviewButton {
        background-color: #0d6efd;
        color: white;
        padding: 10px 20px;
        cursor: pointer;
        transition: background-color 0.3s;
        outline: none;
        border: solid ;
    }
    #AddButton {
        background-color: #0d6efd; /* Fill putih */
        color: white; /* Warna teks merah */
        padding: 5px 10px;
        cursor: pointer;
        transition: background-color 0.3s; /* Animasi perubahan warna saat hover */
        outline: none; /* Hapus outline saat tombol mendapatkan fokus */
        border: solid ;
    .card {
        font-family: 'Roboto', sans-serif; /* Ganti 'Roboto' dengan nama font yang Anda inginkan */
        transition: transform 0.2s;
    }
    
    .card:hover {
        transform: scale(1.05);
        filter: brightness(0.9);
    }
</style>
{% endblock meta %}

{% block content %}
    <body>
        <button id="AddButton" class="rounded" data-bs-toggle="modal" data-bs-target="#addModal">Add Books</button>
        <div class="d-flex grid gap-4 flex-wrap m-4" id="product_cards">
    <div class="container">
        <nav class="navbar navbar-expand-lg py-1" style="background-color: #e3f2fd;">
            <div class="container">
                <a class="navbar-brand" >Welcome back, {{ name }}</a>
                <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target=""
                    >
                    <span class="navbar-toggler-icon"></span>
                </button>
    
                <div class="collapse navbar-collapse" id="navmenu">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'profile' %}" >
                                Profile
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#" >
                                About
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">
                                Logout
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'review:show_reviews_specific_user' %}">
                                Edit Review
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>


        <div class="d-flex grid gap-4 flex-wrap m-4" id="books_catalog"></div>
            
        
    </div>

    <div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="addModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="addModalLabel">Add Book</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="bookForm" method="POST">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name" class="form-label">Judul</label>
                            <input id="name" type="text" name="name" class="form-control">
                        </div>
                        <div class="mb-3">
                            <label for="author" class="form-label">Penulis</label>
                            <input id="author" type="text" name="author" class="form-control">
                        </div>
                        <div class="mb-3">
                            <label for="price" class="form-label">Harga</label>
                            <input id="price" type="text" name="price" class="form-control">
                        </div>
                        <div class="mb-3">
                            <label for="year" class="form-label">Tahun</label>
                            <input id="year" type="text" name="year" class="form-control">
                        </div>
                        <div class="mb-3">
                            <label for="genre" class="form-label">Genre</label>
                            <input id="genre" type="text" name="genre" class="form-control">
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Batal</button>
                            <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Simpan Buku</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>

    <script>


        async function getProducts() {
            return fetch("{% url 'add_book:get_book' %}").then((res) => res.json())
        }
        async function refreshProducts() {
            document.getElementById("product_cards").innerHTML = ""
            const products = await getProducts()
            let htmlString = ``
            products.forEach((book) => {
                htmlString += `<div class="d-flex grid gap-4 flex-wrap m-4" id="product_cards">
                                    <div class="card" style="width: 19rem;">
                                        <div class="card-body">
                                            <h5 class="card-title">${ book.fields.name } (${ book.fields.year })</h5>
                                            <h6 class="card-subtitle mb-2 text-body-secondary">${ book.fields.author }</h6>
                                                <ul>
                                                    <li>Genre: ${ book.fields.genre }</li>
                                                    <li>Rating: ${ book.fields.rating }</li>
                                                    <li>Price: $${ book.fields.price }</li>
                                                </ul>
                                            <a href="#" class="btn btn-primary me-3">Review</a>
                                        </div>
                                    </div>
                                </div>` 
            })
            document.getElementById("product_cards").innerHTML = htmlString
        }


        document.getElementById("button_add").onclick = addBook
            function addBook() {
                fetch("{% url 'add_book:add_book' %}", {
                    method: "POST",
                    body: new FormData(document.querySelector('#bookForm')),
                }).then(refreshProducts)

                return false;
            }
        async function getBooks() {
            return fetch("{% url 'book:get_books' %}").then((res) => res.json())
        }
    
        async function refreshCatalog() {
            let htmlString = ''
            document.getElementById("books_catalog").innerHTML = ""
            const books = await getBooks()
            books.forEach((book) => {
                const bookId = book.id;

                htmlString +=`   
                <div class="card mb-4" data-book-pk="${ book.pk }" style="width: 19rem;">
                    <div class="card-body">
                        <h5 class="card-title"><strong>${ book.fields.name } (${ book.fields.year }s)</strong></h5>
                        <h6 class="card-subtitle mb-2 text-muted">${ book.fields.author }</h6>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">Genre: ${ book.fields.genre }</li>
                            <li class="list-group-item">Rating: ${ book.fields.rating }</li>
                        </ul>
                    </div>
                    <div class="card-footer">
                        <button class="rounded review-button ReviewButton mx-auto" data-book-pk="${ book.pk }">
                            <i class="bi bi-pencil" style="color: white;"></i> Review
                        </button>
                    </div>
                </div>`
            });
            document.getElementById("books_catalog").innerHTML += htmlString;

            document.querySelectorAll(".review-button").forEach((button) => {
                button.addEventListener("click", function (event) {
                    event.stopPropagation();
                    const bookPk = this.getAttribute("data-book-pk");
                    const url = `/review/show-reviews/${bookPk}/`; 
                    window.location.href = url;
                });
            });
            document.querySelectorAll(".card").forEach((card) => {
                card.addEventListener("click", function () {
                    const bookPk = this.getAttribute("data-book-pk");
                    const url = `/edit_book/show/${bookPk}/`; 
                    window.location.href = url;
                });
            });
        }
        refreshCatalog()

    </script>

{% endblock content %}